on:
  push: {}
  pull_request: {}

name: Lint

jobs:
  alejandra:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: alejandra check
        run: nix develop -c alejandra --check .

  prettier:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: npm install
        run: nix develop -c npm install
      - name: prettier check
        run: nix develop -c npm exec -- prettier --check 'src/**/*.ts'
